#!/bin/bash
	sleep .5
	echo -e "........................................................\n"	
	sleep .5
	echo -e "........................................................\n"	
	sleep .5
	echo -e "........................................................\n"
	echo -e "  _   _   _   _   _   _   _   _   _   _   _   _   _ \n"
	echo -e " / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \\n"
	echo -e "(               CloudLauncher                       )\n"
	echo -e " \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \n"
	sleep .5
	echo -e "........................................................\n"	
	sleep .5
	echo -e "........................................................\n"
	sleep .5
	echo -e ".......What would you like to launch today? Testing to see if this works............\n\n"

# Main Menu Loop - This will be the menu that starts the "triage" and brings the user to select the proper template.

while [[ ${can_continue}=true ]]; do
	echo -e "Main Menu - Select a Template to Launch"
	echo -e "\n1. Single VPC with 4 subnets"
	echo -e "\n2. One EC2 Instance"
	echo -e "\n3. Two EC2 Instances"
	echo -e "\n4. Three EC2 Instances"
	echo -e "\n5. Four EC2 Instances"
	echo -e "\n6. One S3 Bucket"
	echo -e "\n\nPress q to quit the program."

read input

# Input of parameters prompt to go here

# This section will need to have another question section to specify the parameters after the selection
# It would be a good idea to put this in other scripts so that it could keep this page alot cleaner. 
# Maybe there could be another script for each of the main categories of templates that allowed for the input 
# of parameters? I think the scripts could be located a folder buried in the main folder, like /bin/bash or
# something like that, with the reference in the script within this main script. 

# Launch script for 01 - VPC with 4 Subnets
# Don't test this one until you get the parameters option set!!!!

if [[ $input -eq 1 ]]; then
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15 
	echo -e "."
	sleep .15
	echo -e "Launching VPC with 4 Subnets....."
	# echo -e "$(aws cloudformation create-stack --stack-name myteststack --template-body file:///home/zackry/cloudlauncher/AWS_CloudFormation_Launcher/templates/01_VPC_with_4_Subnets.yml)"
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1 
	echo -e "."
	sleep 1
	echo -e "Launch Successful!." 
	# echo -e "$(aws cloudformation wait stack-create-complete --stack-name myteststack)"
	# echo -e "$(aws cloudformation describe-stack-resources --stack-name myteststack)\n.\nLaunch successful!!!\n."


# Launch command for 02 - 1 EC2 instance 
elif [[ $input -eq 2 ]]; then
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15 
	echo -e "."
	sleep .15
	echo -e "Launching 1 EC2 Instance....."
	# echo -e "$(aws cloudformation create-stack --stack-name myteststack --template-body file:///home/zackry/cloudlauncher/AWS_CloudFormation_Launcher/templates/02_2_EC2_NO_PARAMETERS.yml)"
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1 
	echo -e "."
	sleep 1
	echo -e "Launch Successful!" 
	# echo -e "$(aws cloudformation wait stack-create-complete --stack-name myteststack)"
	# echo -e "$(aws cloudformation describe-stack-resources --stack-name myteststack)\n.\nLaunch successful!!!\n."

# Launch command for 02 - 2 EC2 instances 

elif [[ $input -eq 3 ]]; then
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15 
	echo -e "."
	sleep .15
	echo -e "Launching 2 EC2 Instances....."
	# echo -e "$(aws cloudformation create-stack --stack-name myteststack --template-body file:///home/zackry/cloudlauncher/AWS_CloudFormation_Launcher/templates/02_2_EC2_NO_PARAMETERS.yml)"
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1 
	echo -e "."
	sleep 1
	echo -e "Launch Successful!" 
	# echo -e "$(aws cloudformation wait stack-create-complete --stack-name myteststack)"
	# echo -e "$(aws cloudformation describe-stack-resources --stack-name myteststack)\n.\nLaunch successful!!!\n."

# Launch command for 02 - 3 EC2 instances
elif [[ $input -eq 4 ]]; then
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15 
	echo -e "."
	sleep .15
	echo -e "Launching 3 EC2 Instances....."
	# echo -e "$(aws cloudformation create-stack --stack-name myteststack --template-body file:///home/zackry/cloudlauncher/AWS_CloudFormation_Launcher/templates/02_2_EC2_NO_PARAMETERS.yml)"
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1 
	echo -e "."
	sleep 1
	echo -e "Launch Successful!" 
	# echo -e "$(aws cloudformation wait stack-create-complete --stack-name myteststack)"
	# echo -e "$(aws cloudformation describe-stack-resources --stack-name myteststack)\n.\nLaunch successful!!!\n."

# Launch command for 02 - 4 EC2 instances 
elif [[ $input -eq 5 ]]; then
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15 
	echo -e "."
	sleep .15
	echo -e "Launching 4 EC2 Instances....."
	# echo -e "$(aws cloudformation create-stack --stack-name myteststack --template-body file:///home/zackry/cloudlauncher/AWS_CloudFormation_Launcher/templates/02_2_EC2_NO_PARAMETERS.yml)"
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1 
	echo -e "."
	sleep 1
	echo -e "Launch Successful!" 
	# echo -e "$(aws cloudformation wait stack-create-complete --stack-name myteststack)"
	# echo -e "$(aws cloudformation describe-stack-resources --stack-name myteststack)\n.\nLaunch successful!!!\n."

# Launch command for 03 - 1 S3 Bucket
elif [[ $input -eq 6 ]]; then
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15
	echo -e "."
	sleep .15 
	echo -e "."
	sleep .15
	echo -e "Launching 1 S3 Bucket....."
	# echo -e "$(aws cloudformation create-stack --stack-name myteststack --template-body file:///home/zackry/cloudlauncher/AWS_CloudFormation_Launcher/templates/03_1_S3_Bucket_NO_Parameters.yml)"
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1
	echo -e "."
	sleep 1 
	echo -e "."
	sleep 1
	echo -e "Launch Successful!" 
	# echo -e "$(aws cloudformation wait stack-create-complete --stack-name myteststack)"
	# echo -e "$(aws cloudformation describe-stack-resources --stack-name myteststack)\n.\nLaunch successful!!!\n."
elif [[ $input = q ]]; then
	echo -e "\n.\n.\n.\n.\nQuitting Now\n"
	sleep .25
	echo -e "."	
	sleep .25
	echo -e "."	
	sleep .25
	echo -e "."
	sleep .25
	echo -e "Goodbye..."
	break

else
	echo -e "\n.\n.\n.\n.Please enter a valid response (1-5 or q to quit)\n\n"
fi
done
