
Description: Template for launching a single EC2 instance
Parameters: 
  VMInstanceType:
    Description: Type of VM that the user wants to launch 
    Type: String
  VMInstanceName: 
    Description: Name for the instance
    Type: String
  KeyPair: 
    Description: Select the keypair to SSH into instance
    Type: String
Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      ImageId: ami-026b57f3c383c2eec
      InstanceType: !Ref VMInstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref VMInstanceName