
Description: Template for launching 2 unique EC2s at once.  
Parameters: 
### VM1 Specs
  VM1InstanceType:
    Description: Type of VM that the user wants to launch 
    Type: String
  VM1InstanceName: 
    Description: Name for the instance
    Type: String
  KeyPair1: 
    Description: Select the keypair to SSH into instance
    Type: String
 
### VM2 Specs 
  VM2InstanceType:
    Description: Type of VM that the user wants to launch 
    Type: String
  VM2InstanceName: 
    Description: Name for the instance
    Type: String
  KeyPair2: 
    Description: Select the keypair to SSH into instance
    Type: String


Resources:
###VM1 Resource
  VMInstance1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair1
      ImageId: ami-026b57f3c383c2eec
      InstanceType: !Ref VM1InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref VM1InstanceName
###VM2 Resource
  VMInstance2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair2
      ImageId: ami-026b57f3c383c2eec
      InstanceType: !Ref VM2InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref VM2InstanceName

