AWSTemplateFormatVersion: 2010-09-09
Description: Simple EC2 instance with no parameters to test functionality

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-026b57f3c383c2eec
      InstanceType: t2.micro
      
      Tags:
        - Key: 'Name'
          Value: 'Test EC2'