
Description: Template for launching 3 VMs at once
Parameters: 
 
### VM1 Specs
  VM1InstanceType:
    Description: Type of VM that the user wants to launch 
    Type: String
  VM1InstanceName: 
    Description: Name for the instance
    Type: String
  KeyPair1: 
    Description: Select the keypair to SSH into instance
    Type: String
 
### VM2 Specs 
  VM2InstanceType:
    Description: Type of VM that the user wants to launch 
    Type: String
  VM2InstanceName: 
    Description: Name for the instance
    Type: String
  KeyPair2: 
    Description: Select the keypair to SSH into instance
    Type: String

### VM3 Specs 
  VM3InstanceType:
    Description: Type of VM that the user wants to launch 
    Type: String
  VM3InstanceName: 
    Description: Name for the instance
    Type: String
  KeyPair3: 
    Description: Select the keypair to SSH into instance
    Type: String


### VM4 Specs 
  VM4InstanceType:
    Description: Type of VM that the user wants to launch 
    Type: String
  VM4InstanceName: 
    Description: Name for the instance
    Type: String
  KeyPair4: 
    Description: Select the keypair to SSH into instance
    Type: String


Resources:
###VM1 Resource
  VMInstance1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair1
      ImageId: ami-026b57f3c383c2eec
      InstanceType: !Ref VM1InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref VM1InstanceName
###VM2 Resource
  VMInstance2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair2
      ImageId: ami-026b57f3c383c2eec
      InstanceType: !Ref VM2InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref VM2InstanceName

###VM3 Resource
  VMInstance3:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair3
      ImageId: ami-026b57f3c383c2eec
      InstanceType: !Ref VM3InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref VM3InstanceName


###VM4 Resource
  VMInstance4:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair4
      ImageId: ami-026b57f3c383c2eec
      InstanceType: !Ref VM4InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref VM4InstanceName