AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket Template
Parameters: 
  BucketName: 
    Description: Set a unique name for your S3 Bucket
    Type: String
    Default: Bucket1234 
Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Ref BucketName
      LifecycleConfiguration: 
      Tags:
        - Key: Name
          Value: !Ref BucketName